// These are reviewable, non-canonical additions. They must not alter or be quoted as original story text.
export const PARENT_COMMUNICATION_PREMISE_STATUS = 'approved_for_game';

export const PARENT_COMMUNICATION_TYPES = {
  'xiaoming_dinosaur:uniform_storage_then_restore': 'complaint',
  'xiaoming_dinosaur:ask_xiaoming_first': 'sharing',
  'xiaoming_dinosaur:label_fixed_position': 'sharing',
  'xiaoli_sunlight:too_fast_sunlight_attempt': 'complaint',
  'xiaoli_sunlight:three_light_zones': 'sharing',
  'xiaoli_sunlight:move_everyone_to_shade': 'complaint',
  'week2_toy_preference:offer_multiple_textures': 'complaint',
  'week2_toy_preference:follow_familiar_texture': 'sharing',
  'week2_toy_preference:use_sound_toy': 'complaint',
  'week2_sandpit_parallel_play:require_spoken_counting': 'complaint',
  'week2_sandpit_parallel_play:add_visual_turn_line': 'sharing',
  'week2_sandpit_parallel_play:adult_takes_over_play': 'complaint',
  'week3_picture_book_emotion:high_arousal_story': 'complaint',
  'week3_picture_book_emotion:repetitive_language_rhythm': 'sharing',
  'week3_picture_book_emotion:children_choose_book': 'sharing',
  'week3_structured_movement:high_intensity_first': 'complaint',
  'week3_structured_movement:low_intensity_then_build': 'sharing',
  'week3_structured_movement:parallel_pacing_groups': 'sharing',
  'week4_charity_exhibition:select_for_visual_impact': 'complaint',
  'week4_charity_exhibition:child_assent_first': 'sharing',
  'week4_charity_exhibition:internal_review_before_release': 'sharing',
  'week4_group_interaction:single_queue_rule': 'complaint',
  'week4_group_interaction:add_second_material_set': 'sharing',
  'week4_group_interaction:remove_one_child_only': 'complaint',
  'week5_blocks_puzzle_prompting:give_exact_answer': 'complaint',
  'week5_blocks_puzzle_prompting:hint_edge_pieces': 'sharing',
  'week5_blocks_puzzle_prompting:rotate_puzzle_view': 'sharing',
  'week6_meal_sensory:separate_mixed_food': 'sharing',
  'week6_meal_sensory:verbal_choice_and_wait': 'complaint',
  'week7_final_observation:record_only_visible_changes': 'complaint',
  'week7_final_observation:one_detail_per_child': 'sharing',
  'week7_final_observation:prioritize_overlooked_children': 'sharing',
};

export function getParentCommunicationType(outcomeId) {
  return PARENT_COMMUNICATION_TYPES[outcomeId] ?? 'complaint';
}

export const PARENT_COMMUNICATION_PREMISES = [
  {
    outcomeId: 'xiaoming_dinosaur:uniform_storage_then_restore',
    week: 1,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '小明回家后，比平时更频繁地检查几件常用小物是否还在原来的位置。',
      '家长移动其中一件物品时，小明立刻把它放回原位，又连续确认了两次。',
    ],
    causalChain: [
      '照护所里，小恐龙曾被移出固定格，小明出现快速寻找和呼吸变急；发现后，小恐龙被放回。',
      '这次意外变化带来的警觉没有立刻完全消退，回家后表现为更频繁地确认熟悉物品的位置。',
      '家长只看见回家后的反复确认，不知道照护所里移动过小恐龙，因此向老师核实当天是否发生过位置变化。',
    ],
    parentKnownFacts: ['小明今晚反复检查熟悉物品的位置', '他在物品被移动时明显着急'],
    questionFocus: '照护所是否临时改变过固定物品的位置，以及以后怎样避免突然变化。',
    parentFirstMessage: '老师，小明今天回家后一直在检查几样东西是不是还放在原来的位置，我挪了一件，他马上又放回去，还确认了好几次。照护所今天是不是动过他平时固定放的东西？',
  },
  {
    outcomeId: 'xiaoming_dinosaur:ask_xiaoming_first',
    week: 1,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上整理玩具时，小明先看向家长，再指向自己平时使用的那个位置。',
      '家长确认后没有移动，他才继续整理，过程比以往被直接调整物品时平稳。',
    ],
    causalChain: [
      '照护所里，老师在移动小恐龙前先询问，小明用注视和指向表达了固定位置，老师据此保留原状。',
      '同一天在家整理时，小明再次使用注视和指向表达位置偏好，并在家长确认后继续活动。',
      '家长把这看作一种可被理解的表达方式，但不知道照护所当天如何回应，因此来询问老师是否也观察到相似沟通。',
    ],
    parentKnownFacts: ['小明今晚用注视和指向表达物品应放在哪里', '家长确认后，他能继续整理'],
    questionFocus: '老师是否先询问并理解了小明的非口语表达，家庭是否可以沿用同样方式。',
    parentFirstMessage: '老师，今晚整理玩具时，小明先看我，再指了指他平常放东西的位置，等我确认不动以后才继续。你们今天是不是也先问了他的意思？这种做法我们在家要不要保持一致？',
  },
  {
    outcomeId: 'xiaoming_dinosaur:label_fixed_position',
    week: 1,
    informationChannels: ['照护所活动照片', '家长既有观察'],
    addedBackground: [
      '照护所发布的当天活动照片拍到了玩具架，照片里能看见“小明的小恐龙”标签。',
      '家长知道小明在家也会坚持几件常用物品放在固定位置，但不清楚标签是临时安排还是长期支持。',
      '本选项中，稳定的固定位置是对小明直接有意义的支持；标签主要是给照护者看的协作提示，用来避免整理时误收，并帮助区分个人支持和公共玩具边界。',
    ],
    causalChain: [
      '照护所为小恐龙保留固定格，维持小明已经熟悉的稳定位置；同时贴上标签，提醒整理玩具的成人不要误收。',
      '家长从活动照片看见标签，并联系到小明在家的固定摆放习惯，但无法判断标签是给小明看的支持，还是给照护者看的协作提示。',
      '家长因此询问老师：固定位置对小明的意义是什么、标签和公共收纳边界如何理解、家庭是否只需维持原有摆放，还是需要额外加标记。',
    ],
    parentKnownFacts: ['活动照片里出现了写有小明名字的小恐龙固定格', '小明在家也有固定摆放习惯'],
    questionFocus: '区分固定位置对小明的意义、标签对成人协作的作用、公共与个人物品边界，以及家庭是否只需维持既有摆放或在必要时加提示。',
    parentFirstMessage: '老师，我在今天的活动照片里看到架子上贴了“小明的小恐龙”。这个固定格主要是为了让他更容易确认位置吗？家里也需要做类似标记吗？',
  },
  {
    outcomeId: 'xiaoli_sunlight:too_fast_sunlight_attempt',
    week: 1,
    informationChannels: ['接回孩子时的现场观察', '家庭观察'],
    addedBackground: [
      '离开照护所时，小丽走到有直射光的门口便停下、抬手挡眼，等家长带她绕到阴影处才继续走。',
      '回家路上遇到较亮路段时，她比平时更早开始回避。',
    ],
    causalChain: [
      '户外活动中，小丽被带向阳光区，走了两步后挡眼、身体绷紧并后退，随后回到树荫。',
      '当天离所时，她在相似光线下再次迅速回避，家长直接观察到这一反应。',
      '家长不知道白天发生过什么，只能判断今天对强光的承受似乎更低，因此向老师核实户外活动是否推进过快。',
    ],
    parentKnownFacts: ['小丽离所时在直射光前停下并挡眼', '绕到阴影后她才继续走'],
    questionFocus: '白天是否出现过强光不适，以及之后会不会继续强行练习。',
    parentFirstMessage: '老师，小丽今天一走到门口有太阳的地方就停下来挡眼，绕到阴影里才肯继续。她白天户外活动时是不是也对光线很不舒服？当时有带她往亮处走吗？',
  },
  {
    outcomeId: 'xiaoli_sunlight:three_light_zones',
    week: 1,
    constructionType: 'positive_strategy_transfer',
    difficultyTier: 'complex',
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上家长打开阳台门时，小丽没有像以往那样立即退回室内，而是把小凳子拖到窗帘影子与亮处交界的位置才坐下。',
      '她没有继续往最亮处走，但也没有完全离开阳台；家长一度以为她突然“不怕光了”。',
    ],
    causalChain: [
      '照护所设置三个光照区域，让小丽自行选择；她从树荫移动到半阴处并停留。',
      '回家后，小丽把“寻找自己能承受的光线边界”迁移到了阳台，但家长只看到她罕见地没有完全退出。',
      '家长把变化暂时理解成光敏感减轻，向老师询问白天发生了什么；老师需要说明这更可能是她找到了可退回、可选择的位置，不能据此判断她已经不怕光。',
    ],
    parentKnownFacts: ['小丽今晚没有完全退出阳台', '她主动把凳子放在窗帘影子与亮处交界的位置', '她仍没有进入最亮处'],
    parentInterpretation: '小丽可能突然没有以前那么怕光了。',
    actualRelationship: '照护所提供选择与可退回空间后，小丽可能迁移了寻找可承受边界的策略；这不等于感官敏感已经减轻。',
    alternativeExplanations: ['当晚光线强度与平时不同', '小丽当天整体状态较稳定'],
    questionFocus: '区分“感官敏感减轻”与“学会选择可承受位置”，并讨论家庭如何保留选择和退路。',
    parentFirstMessage: '老师，小丽今晚没有像以前那样一开阳台门就退回去，而是把凳子拖到窗帘影子边上才坐下。我本来以为她没那么怕光了，但她还是没有往最亮的地方走。你们今天户外活动是不是换了什么做法？',
  },
  {
    outcomeId: 'xiaoli_sunlight:move_everyone_to_shade',
    week: 1,
    informationChannels: ['照护所活动照片', '家长既有观察'],
    addedBackground: [
      '家长从当天活动照片看见所有孩子都集中在树荫下。',
      '家长知道小丽会回避直射光，因此担心老师为了她改变了整个小组的活动，而小丽也可能因此被其他人视为特殊原因。',
    ],
    causalChain: [
      '照护所为维持秩序，把所有孩子带到树荫下；现场虽然安静，但并未同时满足每个孩子的调节需要。',
      '家长只能从照片看到全组都在树荫，无法知道这项安排是出于秩序还是个别需要。',
      '家长结合小丽对强光敏感的既有情况，担心群体安排是否被归因于她，于是向老师确认。',
    ],
    parentKnownFacts: ['照片里所有孩子都在树荫下', '小丽平时会回避直射光'],
    questionFocus: '是否为了小丽统一改变全组活动，以及老师怎样同时照顾不同孩子的需要。',
    parentFirstMessage: '老师，我看今天的照片里所有孩子都到树荫下活动了。是因为小丽不舒服才把大家都移过去的吗？我担心这样会不会让她显得像是影响了其他孩子。',
  },
  {
    outcomeId: 'week2_toy_preference:offer_multiple_textures',
    week: 2,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '回家后，家长拿出一个新买的软胶玩具，孩子碰了一下便推远，又立即回到平时使用的磨砂积木旁。',
      '这种回避比家长原先预期更快，家长想知道白天是否已经接触过多种新触感。',
    ],
    causalChain: [
      '照护所一次呈现多种新材质，孩子短暂触碰后把其中几块推远。',
      '当天回家，他面对另一件陌生触感时再次迅速推开，并回到熟悉材质。',
      '家长只掌握家庭侧反应，不能确定是单纯偏好、累积负荷还是其他原因，因此向老师询问白天材料呈现的数量和节奏。',
    ],
    parentKnownFacts: ['孩子回家后迅速推开一件陌生材质', '他随后回到熟悉的磨砂玩具旁'],
    questionFocus: '白天是否一次提供了太多新材质，以及下一次怎样缩小变化。',
    parentFirstMessage: '老师，孩子今天回家碰了一下我新买的软胶玩具就马上推开，又回去摸那几块磨砂积木。白天玩具室是不是一次拿了好几种不同手感的玩具给他？会不会变化有点多？',
  },
  {
    outcomeId: 'week2_toy_preference:follow_familiar_texture',
    week: 2,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上家长坐在旁边拿起同样的磨砂积木，没有要求孩子换玩法。',
      '孩子没有把家长的积木推走，过了一会儿还把自己的一块积木往家长方向挪近了一点。',
    ],
    causalChain: [
      '照护所里，老师跟随孩子使用熟悉材质；在没有催促更换的情况下，孩子把积木往老师方向挪近。',
      '家长在家采用相似的低压力并行方式，也观察到孩子允许距离缩短。',
      '家长不把一次靠近直接解释为能力突破，而是询问老师是否看见相同模式以及该如何继续。',
    ],
    parentKnownFacts: ['家长没有要求孩子换玩具', '孩子允许家长并行使用相同积木并主动挪近一点'],
    questionFocus: '跟随熟悉偏好是否有助于建立互动，以及怎样避免过度解读一次反应。',
    parentFirstMessage: '老师，今晚我没催他换玩具，只在旁边拿了一块同样的磨砂积木。他后来把自己的积木往我这边挪了一点。你们今天是不是也先陪着他玩同一种积木，没有催他换？',
  },
  {
    outcomeId: 'week2_toy_preference:use_sound_toy',
    week: 2,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '回家后，家里的发声玩具刚响，孩子便迅速按停声音，随后在玩具架前来回走。',
      '家长发现他对声音的反应比平时更快，怀疑当天已经承受过较多声音刺激。',
    ],
    causalChain: [
      '照护所用声音玩具吸引注意，孩子明显烦躁并在架子前来回走。',
      '回家后相似声音再次出现时，孩子立即关闭并重复来回走动。',
      '家长不能从这一反应确定白天发生过什么，因此询问老师是否使用了声音玩具以及当时如何停止刺激。',
    ],
    parentKnownFacts: ['发声玩具一响，孩子立即按停', '随后他在玩具架前来回走'],
    questionFocus: '白天是否额外使用声音刺激，以及老师是否识别出烦躁信号。',
    parentFirstMessage: '老师，孩子今天回家一听到发声玩具就马上按掉，之后还在架子前来回走。玩具室白天是不是也用过声音玩具吸引他？他当时有没有表现得不舒服？',
  },
  {
    outcomeId: 'week2_sandpit_parallel_play:require_spoken_counting',
    week: 2,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '放学后经过小区沙坑时，孩子原本靠近准备玩；家长一提“要不要轮流数数”，他立刻停下并离开沙坑边。',
      '家长知道孩子平时可以和别人并排玩沙，因此怀疑当天的活动是否把口语要求加进了原有玩法。',
    ],
    causalChain: [
      '照护所给原本顺畅的递铲动作加入轮流报数后，动作中断，其中一个孩子离开。',
      '回家路上，类似的口语轮流提示再次让孩子退出本来愿意接近的沙坑活动。',
      '家长只看到提示与退出在家庭场景中相邻发生，因此向老师核实白天是否也出现相同情况，而不是直接断定原因。',
    ],
    parentKnownFacts: ['孩子原本愿意靠近沙坑', '听见轮流数数的建议后立刻退出'],
    questionFocus: '白天是否增加了口语任务，以及口语要求是否打断了已有合作。',
    parentFirstMessage: '老师，孩子放学后本来想去沙坑，我一说“要不要轮流数数”，他马上就走开了。今天沙坑活动是不是也要求他们开口报数？他当时有没有因此停下来？',
  },
  {
    outcomeId: 'week2_sandpit_parallel_play:add_visual_turn_line',
    week: 2,
    constructionType: 'cross_context_strategy_transfer_with_misattribution',
    difficultyTier: 'complex',
    informationChannels: ['家庭观察', '孩子的动作表达'],
    addedBackground: [
      '晚上和手足一起做手工时，孩子先拿一条纸胶带贴在桌子中间，把两边的材料分开。',
      '家长起初担心他越来越不愿意分享；但活动开始后，孩子会把正在共用的胶水沿着胶带边缘推给手足，两个人没有争抢。',
    ],
    causalChain: [
      '照护所里，老师在沙面增加一条轮换线，两个孩子顺着线调整递铲方向，没有中断原有节奏。',
      '孩子把视觉边界迁移到不同的家庭活动：先明确各自空间，再沿边界传递共用材料。',
      '家长只看到“先分开”这个动作，最初误以为这是拒绝分享；老师需要帮助家长看到，清楚边界反而支持了后续轮换。',
    ],
    parentKnownFacts: ['孩子主动用纸胶带分开两边材料', '之后他会沿胶带边缘把共用胶水推给手足', '整个过程没有发生争抢'],
    parentInterpretation: '孩子先把材料分开，可能表示他越来越不愿意分享。',
    actualRelationship: '明确空间边界降低了不确定性，使孩子更容易参与轮换和共享。',
    alternativeExplanations: ['家庭活动人数较少', '手足当晚没有主动越过边界'],
    questionFocus: '纠正“划清边界就是拒绝分享”的误解，并说明结构怎样支持合作。',
    parentFirstMessage: '老师，孩子今晚做手工前先拿胶带把桌子分成两边，我一开始还担心他是不是更不愿意分享了。可是后来他会把共用的胶水沿着胶带推给家里人，两个人反而没抢。你们今天是不是也用过这种边界？',
  },
  {
    outcomeId: 'week2_sandpit_parallel_play:adult_takes_over_play',
    week: 2,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上搭积木时，家长伸手帮忙把结构搭稳，孩子立即退到旁边，只看着家长继续，不再碰积木。',
      '家长注意到他不是发脾气，而是在成人接手后停止参与。',
    ],
    causalChain: [
      '照护所里，成人加入后很快把沙堡搭出形状，但其中一个孩子退到边上停止动作。',
      '家庭活动中，成人帮助再次与孩子退出同时出现。',
      '家长不能确认两次是否同一原因，于是向老师询问白天成人介入到什么程度，以及孩子当时怎样反应。',
    ],
    parentKnownFacts: ['家长接手搭积木后，孩子退到旁边停止参与', '孩子没有继续尝试'],
    questionFocus: '成人帮助是否过多，以致孩子从参与者变成旁观者。',
    parentFirstMessage: '老师，今晚我一伸手帮他搭积木，他就退到旁边，只看我做，自己不再碰了。今天沙坑活动里是不是也有大人帮得比较多？他当时是不是也退出了？',
  },
  {
    outcomeId: 'week3_picture_book_emotion:high_arousal_story',
    week: 3,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '睡前读故事时，家长把声音提高来表现紧张情节，孩子立即捂耳、身体往后缩，并把书推开。',
      '家长知道他平时并非完全拒绝绘本，因此怀疑当天是否已经经历过较强的故事刺激。',
    ],
    causalChain: [
      '照护所选择高唤起的冒险情节，部分孩子兴奋，也有人捂耳、后缩，老师随后放慢声音。',
      '当晚相似的声音和紧张情节再次引出捂耳、后缩与推书。',
      '家长根据可观察反应询问白天的故事内容和讲述强度，不把行为简单解释为不喜欢阅读。',
    ],
    parentKnownFacts: ['提高讲述声音后，孩子捂耳并后缩', '孩子把书推开，但平时并非完全拒绝绘本'],
    questionFocus: '白天故事是否过于刺激，以及老师如何帮助孩子从高唤起状态缓下来。',
    parentFirstMessage: '老师，今晚故事一讲到紧张的地方、声音稍微大一点，他就捂住耳朵往后缩，还把书推开了。今天绘本活动是不是也读了比较刺激的内容？',
  },
  {
    outcomeId: 'week3_picture_book_emotion:repetitive_language_rhythm',
    week: 3,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '孩子回家后主动拿出一本有重复句式的旧绘本。',
      '每次读到同一句时，他就翻到下一页，呼吸和身体动作逐渐放慢，并把整本书听完。',
    ],
    causalChain: [
      '照护所使用重复句式和稳定翻页节奏，孩子们逐渐跟上，房间声音也稳定下来。',
      '家庭阅读中，孩子再次主动选择可预测句式，并借固定节奏持续参与。',
      '家长观察到这种正向参与，向老师询问白天使用了什么节奏，以及是否可以在家沿用。',
    ],
    parentKnownFacts: ['孩子主动选择重复句式绘本', '固定句式出现时他能跟着翻页并逐渐安静'],
    questionFocus: '稳定语言节奏是否帮助参与，以及家庭可怎样选择绘本。',
    parentFirstMessage: '老师，孩子今晚自己拿了那本句子会重复的绘本，每读到重复的那一句就翻页，后来整本都听完了。你们今天讲故事时是不是也用了这种一句一句重复的节奏？',
  },
  {
    outcomeId: 'week3_picture_book_emotion:children_choose_book',
    week: 3,
    constructionType: 'strategy_boundary_with_parent_misattribution',
    difficultyTier: 'complex',
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚间阅读前，家长把书架上一排八本书全部拿出来，让孩子“自己选一本”。',
      '孩子来回看了很久，最后把书全部推开；家长因此怀疑，让孩子自己选择是否反而增加了压力。',
    ],
    causalChain: [
      '照护所让孩子先看封面再选书，虽然选择耗时较长，但阅读时靠近的人更多。',
      '家长在家沿用了“让孩子选择”的方向，却一次提供八本书，选择数量和视觉信息远多于照护所现场。',
      '孩子推开所有书不能直接证明他不适合选择；老师需要区分“拥有选择权”与“同时面对过多选项”。',
    ],
    parentKnownFacts: ['家长一次摆出八本书', '孩子来回看了很久', '最后他把所有书推开'],
    parentInterpretation: '孩子可能不适合自己选择，直接由成人决定会更轻松。',
    actualRelationship: '照护所里的有限选择支持了参与；家庭场景的问题更可能是选项过多，而不是选择权本身。',
    alternativeExplanations: ['孩子当晚已经疲倦', '八本书中没有他当时愿意听的内容'],
    questionFocus: '区分选择权与选择负荷，并给出数量有限、可暂停的家庭做法。',
    parentFirstMessage: '老师，我今晚把一排八本书都拿出来让孩子自己选，他看了很久，最后全推开了。我有点怀疑是不是让他选反而更累，直接替他决定会不会好一点？你们今天让孩子选书时是怎么给选项的？',
  },
  {
    outcomeId: 'week3_structured_movement:high_intensity_first',
    week: 3,
    informationChannels: ['接回孩子后的连续观察'],
    addedBackground: [
      '离所后，孩子仍持续快速跑动和跳跃，回家从活动切换到洗手、吃饭时多次冲开位置，较难停下来。',
      '家长知道孩子高强度运动后通常需要明确的降速过程，因此询问当天活动怎样结束。',
    ],
    causalChain: [
      '照护所前半段活动强度很高，后半段没有顺利降速，排队时出现推挤。',
      '离所后的持续高活动水平和困难转换，为家长提供了当天仍未完全降速的可观察线索。',
      '家长据此询问运动强度与结束安排，而不是把孩子概括为故意兴奋或不守规矩。',
    ],
    parentKnownFacts: ['离所后孩子持续快速跑跳', '回家后的几个转换环节都较难停下'],
    questionFocus: '高强度活动后是否安排了降速和结束预告。',
    parentFirstMessage: '老师，孩子今天离开后还是一直快速跑跳，回家以后，从玩到洗手、吃饭都很难停下来。今天感统活动是不是前面强度很高，结束前没有慢慢降下来？',
  },
  {
    outcomeId: 'week3_structured_movement:low_intensity_then_build',
    week: 3,
    constructionType: 'absence_of_expected_difficulty_with_wrong_explanation',
    difficultyTier: 'complex',
    informationChannels: ['接回孩子时的现场观察', '家庭观察'],
    addedBackground: [
      '孩子离所时能完成穿鞋和出门，回家后也没有像往常某些运动日那样持续冲跑或抗拒停下。',
      '晚间散步时，他先慢慢走过路沿，之后才主动跳了几次；家长反而猜测白天是不是“运动量不够”，所以还留着很多力气。',
    ],
    causalChain: [
      '照护所从低刺激的平衡与伸展开始，再逐渐加入跳跃，原本犹豫的孩子后半段加入。',
      '家长看到的是预期中的困难没有出现：离所转换平稳，晚间也能自己从慢动作进入跳跃。',
      '家长把“仍愿意活动”误解成白天运动不足；老师需要解释，活动价值不只在消耗体力，合适梯度也可能让孩子保留调节能力。',
    ],
    parentKnownFacts: ['孩子离所时穿鞋和出门较顺利', '回家后没有持续冲跑或抗拒停下', '散步时他先慢走，后来才主动跳跃'],
    parentInterpretation: '孩子晚上还有力气活动，可能是白天运动量不够。',
    actualRelationship: '渐进强度可能让孩子参与运动而不过度提高唤醒水平，因此离所后仍保有调节余量。',
    alternativeExplanations: ['孩子当天睡眠或身体状态较好', '晚间环境比平常安静'],
    questionFocus: '纠正“运动就是把体力耗尽”的理解，并说明活动强度与调节状态的关系。',
    parentFirstMessage: '老师，孩子今天穿鞋、出门都挺顺，晚上散步时还先慢慢走、后来自己跳了几下。我本来还在想，是不是白天运动量不够，所以晚上还有这么多力气。你们今天感统活动的强度是怎么安排的？',
  },
  {
    outcomeId: 'week3_structured_movement:parallel_pacing_groups',
    week: 3,
    informationChannels: ['照护所活动照片', '家长既有观察'],
    addedBackground: [
      '活动照片显示感统室同时有两组孩子进行不同节奏的动作。',
      '家长知道自己的孩子投入某种身体活动后，有时不会立刻响应远处的集体口令，因此关心分组后是否有人持续看顾。',
    ],
    causalChain: [
      '照护所采用两个并行节奏，孩子与活动的匹配提高，但两位老师需要频繁切换注意。',
      '家长从照片看见分组，却看不出每位老师的责任区域和现场注意分配。',
      '家长结合自己孩子需要近距离提示的既有情况，提出资源与安全问题，而不是评价其他孩子。',
    ],
    parentKnownFacts: ['照片里有两个同时进行的活动组', '自己的孩子有时需要近距离提示才能从动作中转换'],
    questionFocus: '并行分组时如何分配老师、保持持续看顾并兼顾个体节奏。',
    parentFirstMessage: '老师，我看到今天感统活动分成了两个不同节奏的小组。我家孩子做起运动来，有时顾不上听远处的提醒。当时每组都有老师一直看着吗？两边同时进行时，你们怎么分工？',
  },
  {
    outcomeId: 'week4_charity_exhibition:select_for_visual_impact',
    week: 4,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '家长在家提到“这张画很好看，可以给别人看”时，孩子立即把画翻过去，又把下一张纸收进抽屉。',
      '这种收起作品的动作与孩子在照护所听见作品被反复讨论后的反应相似，但家长不知道白天发生过讨论。',
    ],
    causalChain: [
      '照护所优先讨论视觉冲击强的作品，一名孩子随后把下一张纸收起。',
      '家庭中再次出现“让别人看”的话题时，孩子通过翻面和收起表达不愿继续展示。',
      '家长把动作视为需要核实的边界信号，询问作品是否已被讨论或列入展示，而不假定孩子能够口头说明。',
    ],
    parentKnownFacts: ['提到让别人看画时，孩子把画翻面并收起下一张纸'],
    questionFocus: '作品是否在获得孩子与家长同意前被纳入展示，以及当前材料是否仍停留在内部。',
    parentFirstMessage: '老师，我今晚一说“这张画可以给别人看”，孩子马上把画翻过去，还把下一张纸收起来了。今天照护所是不是讨论过要展示他的作品？现在作品还只是在内部挑选，还是已经列进对外清单了？',
  },
  {
    outcomeId: 'week4_charity_exhibition:child_assent_first',
    week: 4,
    constructionType: 'reversible_assent_with_parent_misattribution',
    difficultyTier: 'complex',
    informationChannels: ['展示确认预览', '家庭观察', '孩子的多模态表达'],
    addedBackground: [
      '家长收到待确认的作品预览，其中一张正是孩子白天曾点头同意展示的作品。',
      '晚上再次询问时，孩子却把同一张作品翻过去并压在手臂下面；家长困惑他为什么白天同意、晚上又反悔。',
    ],
    causalChain: [
      '照护所只选择已经获得孩子点头的作品，现场推进较慢但没有出现明显紧张。',
      '孩子回家后对同一作品作出不同表达，家长容易把它理解成反复无常或白天的点头无效。',
      '老师需要说明，白天的同意在当时有效，但同意可以改变；当前明确的拒绝应触发暂停，而不是要求孩子维持先前决定。',
    ],
    parentKnownFacts: ['预览中的作品曾在白天获得孩子点头', '晚上孩子把同一张作品翻面并压住', '材料仍处于待确认阶段'],
    parentInterpretation: '孩子前后不一致，家长不知道应该以哪一次表达为准。',
    actualRelationship: '同意是持续过程，孩子可以撤回；新的拒绝信号应优先触发暂停和重新确认。',
    alternativeExplanations: ['孩子对白天和晚上的展示语境理解不同', '孩子晚上不想继续讨论作品'],
    questionFocus: '解释同意可以撤回，并明确当前流程应暂停到重新确认。',
    parentFirstMessage: '老师，预览里这张画是他白天点头愿意展示的，可我今晚再问时，他又把同一张画翻过去压住了。我不知道该听哪一次，也担心他只是反复。现在是不是应该先把这张撤下来，再重新确认？',
  },
  {
    outcomeId: 'week4_charity_exhibition:internal_review_before_release',
    week: 4,
    informationChannels: ['家长同意流程文件'],
    addedBackground: [
      '家长收到一份仍标注为“内部确认”的展示范围预览，其中把作品、照片、姓名和说明文字分开列出。',
      '文件没有显示任何内容已经对外发布，家长需要确认哪些项目可以使用。',
    ],
    causalChain: [
      '照护所把传播效果与孩子意愿分别整理，并先进行内部确认。',
      '家长通过正式的预览文件获得当前范围，信息渠道明确且不依赖孩子转述。',
      '家长据此提出具体授权问题，确认最终发布前仍有核对和撤回机会。',
    ],
    parentKnownFacts: ['收到标明内部确认的范围预览', '作品、照片、姓名和说明文字被分项列出', '尚无对外发布标记'],
    questionFocus: '各类信息的使用范围、最终确认节点和撤回方式。',
    parentFirstMessage: '老师，我收到那份“内部确认”的展示预览了，作品、照片、姓名和说明是分开列的。是不是每一项都要分别确认，最终对外之前还会再让我们核对一次？',
  },
  {
    outcomeId: 'week4_group_interaction:single_queue_rule',
    week: 4,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上和家人共用画笔时，孩子一听见“排队、等轮到你”便站得很僵，持续低声抗议，却没有离开桌边。',
      '家长知道孩子在拥挤和等待要求同时出现时较难调节，因此怀疑白天集体活动是否只增加了排队规则。',
    ],
    causalChain: [
      '照护所统一排队后，表面秩序形成，但几个孩子仍身体僵硬并低声抗议。',
      '家庭共用材料时，相同的等待口令再次与僵硬、低声抗议同时出现。',
      '家长依据家庭观察询问白天是否发生材料拥挤，以及老师是否除规则外也调整了环境。',
    ],
    parentKnownFacts: ['孩子听见排队等待后身体僵硬并低声抗议', '他仍留在桌边，显示并非简单拒绝活动'],
    questionFocus: '白天是否只强调排队，以及材料、空间和等待提示是否同时调整。',
    parentFirstMessage: '老师，孩子今晚一听到“排队、等轮到你”就整个人僵住，一直低声抗议，但又没有离开桌边。今天集体活动是不是也让他们排队等彩笔？现场是不是很挤？',
  },
  {
    outcomeId: 'week4_group_interaction:add_second_material_set',
    week: 4,
    constructionType: 'positive_system_effect_with_parent_misattribution',
    difficultyTier: 'complex',
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上孩子和手足画画时，孩子先把一盒彩笔分成两小盒，放到桌子两端，再坐到其中一边。',
      '家长起初担心他是在躲着手足、不愿共用；但两个人整段时间都在同一张桌上画完，没有出现平时的抢笔。',
    ],
    causalChain: [
      '照护所增加第二盒彩笔并分到另一张桌，争抢快速减少，原本快哭的孩子重新坐下。',
      '孩子把“降低材料竞争密度”的安排迁移到家庭场景，最终结果是预期中的争抢没有出现。',
      '家长却可能把分散材料理解成回避共同活动；老师需要区分“保持适当距离”与“退出互动”。',
    ],
    parentKnownFacts: ['孩子主动把一盒彩笔分成两份并放远', '他仍留在同一张桌上与手足一起画', '整段活动没有发生抢笔'],
    parentInterpretation: '孩子把材料分开，可能是在躲着别人、不愿意学习共用。',
    actualRelationship: '分散材料降低了竞争和拥挤，使共同活动得以持续；空间分开不等于社交退出。',
    alternativeExplanations: ['手足当晚状态较平稳', '家庭活动人数比照护所少'],
    questionFocus: '区分环境支持与回避，并说明减少冲突密度怎样保护共同参与。',
    parentFirstMessage: '老师，孩子今晚先把一盒彩笔分成两小盒，放到桌子两边。我一开始担心他是在躲着家里人、不愿意共用，可两个人后来一直在同一张桌上画，也没抢笔。把材料分开到底算回避，还是反而能帮他们一起做完？',
  },
  {
    outcomeId: 'week4_group_interaction:remove_one_child_only',
    week: 4,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '回家和手足共用彩笔时，孩子把整盒彩笔护在身前，反复看向对方的手，即使另一人暂时离开也没有马上放松。',
      '家长由此怀疑白天可能发生过材料争抢，但不知道现场涉及谁，也不知道老师怎样处理。',
    ],
    causalChain: [
      '照护所把最激动的孩子带开安抚，但桌边争抢继续，说明压力还来自材料和空间。',
      '回家后，孩子在相似的共用材料场景中持续护住彩笔并警觉他人靠近。',
      '家长只询问自己孩子所在环境，不要求老师透露其他孩子身份，并关心现场是否处理了共同触发因素。',
    ],
    parentKnownFacts: ['孩子在家护住整盒彩笔并持续观察他人的手', '对方暂时离开后，他仍没有马上放松'],
    questionFocus: '白天是否发生持续争抢，以及处理一个孩子之后是否也调整了材料和空间。',
    parentFirstMessage: '老师，孩子今晚和家里人共用彩笔时一直把整盒彩笔护在身前，对方走开以后他还盯着看了很久。今天桌边是不是发生过争抢？现场后来是怎么处理的，材料或位置有没有调整？',
  },
  {
    outcomeId: 'week5_blocks_puzzle_prompting:give_exact_answer',
    week: 5,
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上拼图卡住时，家长直接指出正确缺口，孩子把那块放好后看了一眼成品，随即起身离开。',
      '家长发现任务虽然完成，孩子却没有继续尝试下一块。',
    ],
    causalChain: [
      '照护所直接指出缺口，拼图很快完成，但孩子看过成品后离开。',
      '家庭中相同的直接答案再次带来快速完成和随即退出。',
      '家长没有把退出解释成没有能力，而是询问白天老师提供了多少帮助，以及是否可以改用更少提示。',
    ],
    parentKnownFacts: ['直接指出位置后，孩子完成一块便离开', '孩子没有继续观察或尝试'],
    questionFocus: '答案式帮助是否替代了探索过程，以及下一次怎样降低提示量。',
    parentFirstMessage: '老师，今晚拼图卡住时我直接告诉他放哪里，他放好以后看了一眼就走了，也没再试下一块。今天你们拼图时是不是也直接指出了答案？会不会帮得太快了？',
  },
  {
    outcomeId: 'week5_blocks_puzzle_prompting:hint_edge_pieces',
    week: 5,
    constructionType: 'help_level_misattribution_across_tasks',
    difficultyTier: 'complex',
    informationChannels: ['家庭观察'],
    addedBackground: [
      '晚上搭轨道时，家长伸手替孩子把接头扣上，孩子立刻把家长的手推开；家长因此担心他开始排斥大人帮助。',
      '稍后家长只把两个带相同纹路的接头放到他面前，没有替他连接，孩子看了一会儿后继续尝试。',
    ],
    causalChain: [
      '照护所只提示先找边角，孩子们虽然试错但没有离开，完成后有孩子抬头看老师。',
      '在不同任务中，孩子拒绝的是成人直接完成关键动作，但仍接受不替代操作的视觉线索。',
      '家长容易把推开手理解成拒绝帮助；老师需要把“拒绝接管”与“完全不接受支持”分开。',
    ],
    parentKnownFacts: ['家长直接替他连接轨道时，他推开了家长的手', '家长只呈现两个相似接头时，他继续观察和尝试'],
    parentInterpretation: '孩子可能开始排斥家长帮助，什么都想自己来。',
    actualRelationship: '孩子对不同帮助层级反应不同；保留关键操作权的提示更容易被接受。',
    alternativeExplanations: ['孩子当时已经知道怎样连接', '家长伸手的时机打断了他的观察'],
    questionFocus: '区分拒绝被替代与拒绝支持，并说明怎样逐级增加提示。',
    parentFirstMessage: '老师，孩子今晚搭轨道时，我一伸手替他扣上接头，他马上把我的手推开。我还以为他开始什么帮助都不要了，可后来我只把两个纹路一样的接头摆出来，他又愿意继续试。你们今天拼图时是怎么拿捏提示多少的？',
  },
  {
    outcomeId: 'week5_blocks_puzzle_prompting:rotate_puzzle_view',
    week: 5,
    informationChannels: ['孩子的动作重现', '家庭观察'],
    addedBackground: [
      '孩子在家拼图卡住后，没有要求家长指出答案，而是自己把整块底板转了一个方向。',
      '停顿一会儿后，他重新观察图案并找到一块可以接上的拼片。',
    ],
    causalChain: [
      '照护所轻轻转动拼图，孩子从新角度自行发现图案线索。',
      '回家后，孩子主动重现转动视角的策略，并继续解决问题。',
      '家长把这看作一次可观察的策略使用，询问老师白天是否示范过，而不推定孩子已经稳定掌握。',
    ],
    parentKnownFacts: ['孩子卡住后主动转动拼图', '改变方向后继续观察并找到线索'],
    questionFocus: '转动视角是否作为非答案式提示，以及如何判断孩子能否自行继续。',
    parentFirstMessage: '老师，孩子今晚拼图卡住以后，自己把底板转了个方向，停了一会儿又找到能接上的一块。你们今天是不是也用过“换个方向看”的办法？',
  },
  {
    outcomeId: 'week6_meal_sensory:separate_mixed_food',
    week: 6,
    informationChannels: ['随身餐盒', '家庭观察'],
    addedBackground: [
      '家长清洗餐盒时看见青菜汁碰到的那一小块米饭被分在旁边，其余米饭吃掉了一部分。',
      '晚餐时家长保留食物分隔，小宇观察后先从没有混到的部分开始吃。',
    ],
    causalChain: [
      '照护所只把被菜汁碰到的一小块米饭分开，小宇手指放松并开始吃未混到的米饭。',
      '餐盒留下可见痕迹，家庭晚餐中相同结构也帮助他开始进食。',
      '家长根据餐盒和家庭观察询问老师具体处理，不把情况简单归为挑食，也不声称已经知道现场经过。',
    ],
    parentKnownFacts: ['餐盒里混到菜汁的一小块饭被分开', '其余米饭吃掉了一部分', '晚餐保留分隔后小宇能开始吃'],
    questionFocus: '白天是否通过局部分隔恢复可理解的结构，以及家庭如何保持一致。',
    parentFirstMessage: '老师，我洗餐盒时看到沾到青菜汁的那一小块饭被单独分在旁边，其他米饭吃了一些。你们今天是不是只把混到的部分分开以后，他才开始吃？家里以后也先这样分开摆吗？',
  },
  {
    outcomeId: 'week6_meal_sensory:verbal_choice_and_wait',
    week: 6,
    informationChannels: ['随身餐盒', '家庭观察'],
    addedBackground: [
      '餐盒带回家时，米饭边缘仍沾着青菜汁，整份食物几乎没有动。',
      '晚餐面对相似摆放时，家长问小宇想先吃哪一种，他没有回答，只看着碗，也没有开始。',
    ],
    causalChain: [
      '照护所只用口头问题让小宇选择并等待，但餐盘混合造成的不确定仍在，他没有开始吃。',
      '餐盒状态向家长提供了食物混合和进食很少的可见事实；家庭中相同口头提问也没有解决困难。',
      '家长据此询问白天是否把困难理解成“不会选”，并建议先处理食物结构或提供非口语选择。',
    ],
    parentKnownFacts: ['餐盒中食物混在一起且几乎未动', '口头询问先吃什么时，小宇只看着碗，没有开始'],
    questionFocus: '困难是否来自食物混合而非缺少口头选择，以及是否需要视觉或指认方式。',
    parentFirstMessage: '老师，今天餐盒里的饭菜混在一起，几乎都没动。晚上我问小宇想先吃哪一种，他也只是看着碗，没有回答。白天是不是也只问他想吃什么、然后一直等？会不会真正卡住他的是食物已经混了？',
  },
  {
    outcomeId: 'week7_final_observation:record_only_visible_changes',
    week: 7,
    informationChannels: ['每周观察摘要'],
    addedBackground: [
      '家长收到本周观察摘要，发现自己的孩子只有笼统的“状态稳定”，没有具体写他参加了什么、何时退出或什么支持有效。',
      '家长知道孩子不常主动求助，担心安静被误当作没有需要。',
    ],
    causalChain: [
      '照护所只详细记录变化明显的孩子，复盘时发现几个安静孩子几乎没有内容。',
      '家长从摘要直接看到自己孩子缺少具体观察，这是明确的文件信息渠道。',
      '家长据此询问是否因为孩子表现安静而被忽略，并要求补充可观察事实。',
    ],
    parentKnownFacts: ['摘要只有“状态稳定”一类笼统结论', '没有活动、退出或有效支持的具体记录', '孩子平时较少主动求助'],
    questionFocus: '安静孩子是否被记录盲区遗漏，以及怎样补做具体观察。',
    parentFirstMessage: '老师，我看这周的观察摘要里，孩子只有一句“状态稳定”，没有写他参加了什么、什么时候停下来，或者什么帮助对他有用。是不是因为他比较安静，就没有被具体记录到？',
  },
  {
    outcomeId: 'week7_final_observation:one_detail_per_child',
    week: 7,
    informationChannels: ['每周观察摘要', '家庭观察'],
    addedBackground: [
      '家长收到一条具体记录：孩子在集体活动开始前先站在边缘观察，看到固定位置空出来后才坐下。',
      '家长在家也见过他先观察位置再加入，因此确认这条记录与家庭经验能够相互印证。',
    ],
    causalChain: [
      '照护所按全体扫一轮，为每个孩子保留至少一个具体细节，使安静孩子也有可交接信息。',
      '家长从摘要获得一个清楚、可核对的现场观察，并与家庭表现对照。',
      '家长不要求老师从一次细节下结论，而是询问下一位照护者会怎样继续验证和使用。',
    ],
    parentKnownFacts: ['摘要记录了孩子先观察位置再加入的具体过程', '家里也出现过相似的先观察后加入'],
    questionFocus: '具体观察如何进入下一阶段支持，以及家庭信息如何补充。',
    parentFirstMessage: '老师，我看到摘要里写他会先站在边上看，等固定位置空出来才坐下，这和我们在家看到的很像。这条观察接下来会怎么用？我还需要补充家里的哪些情况？',
  },
  {
    outcomeId: 'week7_final_observation:prioritize_overlooked_children',
    week: 7,
    constructionType: 'longitudinal_correlation_without_causal_certainty',
    difficultyTier: 'complex',
    informationChannels: ['每周观察摘要', '家庭观察'],
    addedBackground: [
      '新版观察摘要补充了一条过去没有记录的细节：环境声音变大时，孩子会退到门边，但在有人留出距离后能重新靠近。',
      '家长翻看家庭记录，发现最近几次较烦躁的晚上大多发生在较吵的日子之后，但也有一次吵闹活动后并没有明显变化。',
    ],
    causalChain: [
      '照护所优先观察过去最少被记录的孩子，一条新记录与近期情绪波动的时间相对应。',
      '家长把照护所记录与家庭日历对照后发现相关模式，但反例说明声音并不能单独解释所有变化。',
      '家长容易因为终于找到线索而过早确定原因；老师需要肯定线索价值，同时提出继续记录声音、活动、身体状态和有效支持。',
    ],
    parentKnownFacts: ['摘要新增了声音变大、退到门边和重新靠近的过程', '近期较烦躁的晚上多数出现在较吵日之后', '至少有一次吵闹活动后没有明显变化'],
    parentInterpretation: '声音可能就是最近情绪波动的主要原因。',
    actualRelationship: '声音是值得继续验证的情境因素，但现有记录只能支持相关性，不能排除疲劳、身体不适或活动变化。',
    alternativeExplanations: ['睡眠或身体不适', '当天其他活动和流程变化', '支持是否及时出现'],
    questionFocus: '肯定线索但避免确定因果，建立跨场景的持续记录计划。',
    parentFirstMessage: '老师，这次摘要第一次写到声音变大时他会退到门边。我翻了家里的记录，最近几次比较烦躁的晚上大多也是吵闹活动之后，可也有一次完全没事。现在能说主要就是声音造成的吗，还是还要把哪些情况一起记下来？',
  },
];

export function getParentCommunicationPremise(outcomeId) {
  return PARENT_COMMUNICATION_PREMISES.find((premise) => premise.outcomeId === outcomeId) ?? null;
}

export function hydrateParentCommunicationOutcome(outcome) {
  if (!outcome?.id) return outcome;
  const premise = getParentCommunicationPremise(outcome.id);
  if (!premise) {
    return {
      ...outcome,
      parentInitiatedEligible: false,
      eligibilityReason: '没有找到与该事件分支对应的家长沟通背景。',
    };
  }

  return {
    ...outcome,
    parentCommunicationType: getParentCommunicationType(outcome.id),
    communicationPremiseStatus: PARENT_COMMUNICATION_PREMISE_STATUS,
    constructionType: premise.constructionType ?? 'direct_observable_follow_up',
    difficultyTier: premise.difficultyTier ?? 'standard',
    informationChannels: [...premise.informationChannels],
    addedBackground: [...premise.addedBackground],
    causalChain: [...premise.causalChain],
    parentKnownFacts: [...premise.parentKnownFacts],
    parentInterpretation: premise.parentInterpretation ?? null,
    actualRelationship: premise.actualRelationship ?? premise.causalChain.at(-1),
    alternativeExplanations: [...(premise.alternativeExplanations ?? [])],
    questionFocus: premise.questionFocus,
    parentMessage: premise.parentFirstMessage,
    parentInitiatedEligible: true,
    eligibilityReason: '家长沟通补充剧情已审核并接入游戏。',
  };
}
